### PR TITLE
Move to new docs

### PR DESCRIPTION
**Pull request by JordanCheney**
@jklontz this PR will put the new docs onto the website. To keep the docs "live" I think the easiest thing to do is to piggyback on @bhklein's buildbot and rebuild the docs dir on every push to openbr master and the push those changes to master here. How does that sound?

### CODE REVIEW

**Comment by bklare** [comment]
@jklontz  FYI, I am going to merge

@JordanCheney Until the build bot happens, perhaps you can periodically update these docs manually

**Comment by jklontz** [comment]
:+1:

**Comment by bhklein** [comment]
I'm going to start working on auto pushing documentation changes.  I've created an account for the buildbot @openbrbot, @jklontz could you give it access?

**Comment by jklontz** [comment]
@bhklein Do you think it makes more sense to have the buildbot simply host the documentation instead of making continuous commits to this repository?

**Comment by bhklein** [comment]
Yeah I think that would work pretty well.  It avoids polluting this repo with a bunch of commit traffic and having a buildbot github user.  This way we could also host the master documentation as well as the docs of past releases, working some way of archiving the docs automatically when a release is tagged.

**Comment by jklontz** [comment]
So you don't need me to add that account right? Regardless I'm happy committing the docs that correspond to tagged releases here as we've done in the past.

**Comment by bhklein** [comment]
Yes please hold off on adding it.  Pushing the tagged releases to here sounds good to me.

**Pull request merged**
